cwist: include/cwist/core/db/nuke_db.h File Reference
nuke_db.h File Reference
High-Performance Read-Optimal Persistent Store using SQLite.
#include <sqlite3.h>
#include <stdbool.h>
Classes
struct cwist_nuke_db_t
Nuke DB Context.
Macros
#define CWIST_NUKE_OK 0
Return codes for cwist_nuke_init.
Typedefs
typedef struct cwist_nuke_db_t cwist_nuke_db_t
Nuke DB Context.
Functions
int cwist_nuke_init (const char *disk_path, int sync_interval_ms)
Initialize Nuke DB.
int cwist_nuke_sync (void)
Force synchronization from Memory to Disk.
void cwist_nuke_close (void)
Close databases safely. Performs a final synchronization before closing handles.
sqlite3 * cwist_nuke_get_db (void)
Get the raw SQLite3 handle for the In-Memory DB.
void cwist_nuke_signal_handler (int signum)
Internal signal handler. Typically set up by cwist_nuke_init.
Detailed Description
High-Performance Read-Optimal Persistent Store using SQLite.
Concept:
Reads: Always from In-Memory DB (Extreme speed).
Writes: Immediately synchronized to Disk DB via WAL (Durability).
Trade-off: Slightly higher write latency for the sake of guaranteed durability and non-blocking ultra-fast reads.
Definition in file nuke_db.h.
Typedef Documentation
cwist_nuke_db_t
typedef struct cwist_nuke_db_t cwist_nuke_db_t
Nuke DB Context.
Logic:
Init: Load disk DB into Memory DB. Enables WAL mode on disk.
Runtime:
SELECTs happen in Memory.
INSERT/UPDATE/DELETE trigger immediate background sync to Disk on COMMIT.
Periodic: Background thread also performs periodic sync as a fail-safe.
Exit: Catch signals (SIGINT, SIGTERM) and force final Sync.
Function Documentation
cwist_nuke_get_db()
sqlite3 * cwist_nuke_get_db (void)
Get the raw SQLite3 handle for the In-Memory DB.
Returns
Pointer to the active sqlite3* handle. Returns the disk handle when NukeDB is operating in disk-only fallback mode.
Definition at line 338 of file nuke_db.c.
References cwist_nuke_db_t::disk_db, cwist_nuke_db_t::is_disk_mode, and cwist_nuke_db_t::mem_db.
cwist_nuke_init()
int cwist_nuke_init (const char * disk_path, int sync_interval_ms)
Initialize Nuke DB.
Loads the disk database into memory (if it exists). Sets up signal handlers for safe exit (SIGINT, SIGTERM). Starts a background thread for auto-sync if interval > 0.
Parameters
disk_path Path to the persistent database file.
sync_interval_ms Auto-sync interval in ms (0 to disable).
Returns
0 on success, negative on failure (see CWIST_NUKE_ERR_* codes).
Definition at line 243 of file nuke_db.c.
References cwist_nuke_db_t::auto_sync, cwist_get_available_ram(), cwist_nuke_close(), CWIST_NUKE_OK, cwist_nuke_db_t::disk_db, cwist_nuke_db_t::disk_path, cwist_nuke_db_t::is_disk_mode, cwist_nuke_db_t::load_successful, cwist_nuke_db_t::mem_db, and cwist_nuke_db_t::sync_interval_ms.
cwist_nuke_sync()
int cwist_nuke_sync (void)
Force synchronization from Memory to Disk.
Returns
0 on success, -1 on failure.
Definition at line 116 of file nuke_db.c.
References cwist_nuke_db_t::disk_db, cwist_nuke_db_t::is_disk_mode, cwist_nuke_db_t::load_successful, and cwist_nuke_db_t::mem_db.
Referenced by cwist_nuke_close().