cwist: include/cwist/sys/io/cwist_io.h File Reference
cwist_io.h File Reference
Platform Agnostic Async Job Queue Interface.
#include <stddef.h>
#include <stdbool.h>
Typedefs
typedef struct cwist_io_queue cwist_io_queue
Opaque handle for the IO Queue. Backend implementation depends on OS (io_uring, kqueue, select).
typedef void(* cwist_job_func) (void *arg)
Job function signature.
Functions
cwist_io_queue * cwist_io_queue_create (size_t capacity)
Initialize the job queue.
bool cwist_io_queue_submit (cwist_io_queue *q, cwist_job_func func, void *arg)
Submit a job to be executed asynchronously.
void cwist_io_queue_run (cwist_io_queue *q)
Run the event loop. Blocks indefinitely, processing jobs as they complete/trigger.
void cwist_io_queue_destroy (cwist_io_queue *q)
Destroy the queue and free resources.
Detailed Description
Platform Agnostic Async Job Queue Interface.
Definition in file cwist_io.h.
Typedef Documentation
cwist_job_func
typedef void(* cwist_job_func) (void *arg)
Job function signature.
Parameters
arg User-provided argument.
Definition at line 22 of file cwist_io.h.
Function Documentation
cwist_io_queue_create()
cwist_io_queue * cwist_io_queue_create (size_t capacity)
Initialize the job queue.
Parameters
capacity Maximum concurrent jobs/events.
Returns
Pointer to queue handle, or NULL on failure.
Definition at line 20 of file io_select.c.
References cwist_io_queue_create().
Referenced by cwist_io_queue_create().
cwist_io_queue_destroy()
void cwist_io_queue_destroy (cwist_io_queue * q)
Destroy the queue and free resources.
Parameters
q Queue handle.
Definition at line 43 of file io_select.c.
References cwist_io_queue_destroy().
Referenced by cwist_io_queue_destroy().
cwist_io_queue_run()
void cwist_io_queue_run (cwist_io_queue * q)
Run the event loop. Blocks indefinitely, processing jobs as they complete/trigger.
Parameters
q Queue handle.
Definition at line 36 of file io_select.c.
References cwist_io_queue_run().
Referenced by cwist_io_queue_run().
cwist_io_queue_submit()
bool cwist_io_queue_submit (cwist_io_queue * q, cwist_job_func func, void * arg)
Submit a job to be executed asynchronously.
Parameters
q Queue handle.
func Function to execute.
arg Argument to pass to function.
Returns
true on success, false on failure (queue full/error).
Definition at line 29 of file io_select.c.
References cwist_io_queue_submit().
Referenced by cwist_io_queue_submit().