cwist: include/cwist/sys/app/app.h File Reference
app.h File Reference
Core Application Structure and Lifecycle Management.
#include <cwist/net/http/http.h>
#include <cwist/net/http/https.h>
#include <cwist/core/db/sql.h>
#include <cwist/sys/err/cwist_err.h>
#include <cwist/core/macros.h>
#include <cwist/sys/app/big_dumb_reply.h>
#include <ttak/mem_tree/mem_tree.h>
#include <cwist/net/websocket/websocket.h>
Classes
struct cwist_middleware_node
Linked list node for middleware chain.
struct cwist_app
Main Application Context.
struct cwist_file_t
Represents a file loaded into the fixed memory pool.
struct cwist_fix_server_mem
Fixed Server Memory Manager.
Typedefs
typedef void(* cwist_handler_func) (cwist_http_request *req, cwist_http_response *res)
Function pointer type for HTTP route handlers.
typedef void(* cwist_ws_handler_func) (cwist_websocket *ws)
Function pointer type for WebSocket handlers.
typedef void(* cwist_error_handler_func) (cwist_http_request *req, cwist_http_response *res, cwist_http_status_t status)
Function pointer type for error handlers.
typedef void(* cwist_middleware_func) (cwist_http_request *req, cwist_http_response *res, cwist_handler_func next)
Middleware type that receives req/res pair and the next stage in the chain.
typedef struct cwist_middleware_node cwist_middleware_node
Linked list node for middleware chain.
typedef struct cwist_app cwist_app
Main Application Context.
typedef struct cwist_file_t cwist_file_t
Represents a file loaded into the fixed memory pool.
typedef struct cwist_fix_server_mem cwist_fix_server_mem
Fixed Server Memory Manager.
Functions
cwist_app * cwist_app_create (void)
Creates a new CWIST application instance.
void cwist_app_destroy (cwist_app *app)
Destroys the application and frees all resources.
void cwist_app_set_max_memspace (cwist_app *app, size_t size)
Sets the maximum memory space for the static file pool.
void cwist_app_configure_bdr (cwist_app *app, size_t max_bytes, time_t max_entry_age_sec, uint64_t revalidate_hits)
Configures the Big Dumb Reply guardrails.
Middleware
Error Handling Configuration
Routing
void cwist_app_get (cwist_app *app, const char *path, cwist_handler_func handler)
Registers a GET route handler.
cwist_error_t cwist_app_static (cwist_app *app, const char *url_prefix, const char *directory)
Serves a directory of static files at a URL prefix. Files are loaded into the fixed memory pool for Zero-Copy serving.
Startup
Detailed Description
Core Application Structure and Lifecycle Management.
Definition in file app.h.
Typedef Documentation
cwist_app
typedef struct cwist_app cwist_app
Main Application Context.
Manages routing, middleware, database connections, memory pools, and caching strategies (BDR).
cwist_file_t
typedef struct cwist_file_t cwist_file_t
Represents a file loaded into the fixed memory pool.
— Memory Management —
cwist_fix_server_mem
typedef struct cwist_fix_server_mem cwist_fix_server_mem
Fixed Server Memory Manager.
Pre-allocates a large contiguous block of memory to serve static files via Zero-Copy pointer passing. Supports hot-reloading on file change.
cwist_handler_func
typedef void(* cwist_handler_func) (cwist_http_request *req, cwist_http_response *res)
Function pointer type for HTTP route handlers.
Parameters
req Pointer to the HTTP request object.
res Pointer to the HTTP response object.
Definition at line 24 of file app.h.
cwist_ws_handler_func
typedef void(* cwist_ws_handler_func) (cwist_websocket *ws)
Function pointer type for WebSocket handlers.
Parameters
ws Pointer to the WebSocket context.
Definition at line 30 of file app.h.
Function Documentation
cwist_app_configure_bdr()
void cwist_app_configure_bdr (cwist_app * app, size_t max_bytes, time_t max_entry_age_sec, uint64_t revalidate_hits)
Configures the Big Dumb Reply guardrails.
Parameters
app Target app.
max_bytes Maximum bytes to keep in RAM (0 = keep default).
max_entry_age_sec Retire cached replies older than this (<=0 keeps default).
revalidate_hits Force refresh after this many hits (0 = keep default).
Definition at line 743 of file app.c.
References cwist_app::bdr_ctx, and cwist_bdr_set_limits().
cwist_app_create()
cwist_app * cwist_app_create (void)
Creates a new CWIST application instance.
— API —
Returns
Pointer to the allocated app, or NULL on failure.
Definition at line 693 of file app.c.
References cwist_app::bdr_ctx, cwist_bdr_create(), cwist_app::db, cwist_app::db_path, cwist_app::error_handler, cwist_app::max_mem_space, cwist_app::mem_manager, cwist_app::middlewares, cwist_app::nuke_enabled, cwist_app::router, cwist_app::ssl_ctx, and cwist_app::static_dirs.
cwist_app_destroy()
void cwist_app_destroy (cwist_app * app)
Destroys the application and frees all resources.
Parameters
app Pointer to the app to destroy.
Definition at line 748 of file app.c.
References cwist_app::bdr_ctx, cwist_bdr_destroy(), cwist_nuke_close(), cwist_app::db, cwist_app::db_path, cwist_fix_server_mem::file_tree, cwist_fix_server_mem::files, cwist_file_t::fs_path, cwist_app::mem_manager, cwist_app::middlewares, cwist_file_t::node, cwist_app::nuke_enabled, cwist_file_t::path, cwist_app::router, cwist_app::ssl_ctx, and cwist_app::static_dirs.
cwist_app_set_max_memspace()
void cwist_app_set_max_memspace (cwist_app * app, size_t size)
Sets the maximum memory space for the static file pool.
Parameters
app Pointer to the app.
size Size in bytes (Use macros like CWIST_MIB(64)).
Definition at line 735 of file app.c.
References cwist_app::max_mem_space.
cwist_app_static()
cwist_error_t cwist_app_static (cwist_app * app, const char * url_prefix, const char * directory)
Serves a directory of static files at a URL prefix. Files are loaded into the fixed memory pool for Zero-Copy serving.
Parameters
app Pointer to the app.
url_prefix URL prefix (e.g., "/static").
directory Local filesystem path.
Note
Additional method helpers can be added as needed.
Definition at line 942 of file app.c.
References cwist_app::static_dirs.