cwist: include/cwist/sys/app/big_dumb_reply.h File Reference
big_dumb_reply.h File Reference
Auto-Caching Layer for repetitive requests.
#include <cwist/core/sstring/sstring.h>
#include <stdint.h>
#include <stdbool.h>
#include <time.h>
Classes
struct bdr_entry_t
Big Dumb Reply Entry. Stores a completely serialized HTTP response blob.
struct cwist_bdr_t
Big Dumb Reply Context. Manages cache buckets and learning parameters.
Typedefs
typedef struct bdr_entry_t bdr_entry_t
Big Dumb Reply Entry. Stores a completely serialized HTTP response blob.
typedef struct cwist_bdr_t cwist_bdr_t
Big Dumb Reply Context. Manages cache buckets and learning parameters.
Functions
cwist_bdr_t * cwist_bdr_create (void)
Creates a BDR context.
void cwist_bdr_destroy (cwist_bdr_t *bdr)
Destroys a BDR context and frees all cached blobs.
const void * cwist_bdr_get (cwist_bdr_t *bdr, const char *method, const char *path, size_t *out_len)
Try to find a cached response.
void cwist_bdr_put (cwist_bdr_t *bdr, const char *method, const char *path, const void *data, size_t len)
Store a response in the cache.
void cwist_bdr_set_limits (cwist_bdr_t *bdr, size_t max_bytes, time_t max_entry_age_sec, uint64_t revalidate_hits)
Adjusts guard-rail policies for the in-memory cache.
Detailed Description
Auto-Caching Layer for repetitive requests.
Definition in file big_dumb_reply.h.
Function Documentation
cwist_bdr_get()
const void * cwist_bdr_get (cwist_bdr_t * bdr, const char * method, const char * path, size_t * out_len)
Try to find a cached response.
Parameters
bdr Context.
method HTTP Method (only GET supported).
path Request path.
out_len [out] Length of the found blob.
Returns
Pointer to the blob if found, NULL otherwise.
Definition at line 209 of file big_dumb_reply.c.
References cwist_bdr_t::bucket_count, cwist_bdr_t::buckets, cwist_bdr_get(), bdr_entry_t::hits, cwist_bdr_t::is_disk_mode, bdr_entry_t::is_stable, bdr_entry_t::len, bdr_entry_t::request_hash, and bdr_entry_t::response_blob.
Referenced by cwist_bdr_get().
cwist_bdr_put()
void cwist_bdr_put (cwist_bdr_t * bdr, const char * method, const char * path, const void * data, size_t len)
Store a response in the cache.
Parameters
bdr Context.
method HTTP Method.
path Request path.
data Serialized response data.
len Length of data.
Definition at line 276 of file big_dumb_reply.c.
References cwist_bdr_t::bucket_count, cwist_bdr_t::buckets, bdr_entry_t::created_at, cwist_bdr_t::current_bytes, cwist_bdr_put(), cwist_bdr_t::disk_db, bdr_entry_t::hits, cwist_bdr_t::is_disk_mode, bdr_entry_t::is_stable, bdr_entry_t::len, bdr_entry_t::request_hash, bdr_entry_t::response_blob, and bdr_entry_t::response_hash.
Referenced by cwist_bdr_put().
cwist_bdr_set_limits()
void cwist_bdr_set_limits (cwist_bdr_t * bdr, size_t max_bytes, time_t max_entry_age_sec, uint64_t revalidate_hits)
Adjusts guard-rail policies for the in-memory cache.
Parameters
bdr Context.
max_bytes Maximum bytes to keep in RAM (0 keeps default).
max_entry_age_sec Time-to-live for cached entries (<=0 keeps default).
revalidate_hits Force relearning after this many hits (0 keeps default).
Definition at line 458 of file big_dumb_reply.c.
References cwist_bdr_set_limits(), cwist_bdr_t::max_bytes, cwist_bdr_t::max_entry_age_sec, and cwist_bdr_t::revalidate_hits.
Referenced by cwist_app_configure_bdr(), and cwist_bdr_set_limits().